set(BUILD_SHARED_LIBS ON)
set(ASSIMP_BUILD_TESTS OFF)
set(ASSIMP_INSTALL_PDB OFF)
set(ASSIMP_WERROR OFF)
set(ASSIMP_BUILD_ASSIMP_TOOLS OFF)

add_subdirectory(${CMAKE_SOURCE_DIR}/third_party/assimp)

set(ASSIMP_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/third_party/assimp/include)

set(ASSIMP_LIBRARIES assimp)
